version: '3.8'

networks:
  b-shuli-network:
    name: b-shuli-network
    driver: bridge

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
  b-shuli-db:
    driver: local
    
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod

    volumes:
      - static_volume:/home/app/assets
      - media_volume:/home/app/media
    expose:
      - 5000
    networks:
      - b-shuli-network
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - PGDATA=/data/postgres
    env_file:
      - ./.env.db
    volumes:
      - b-shuli-db:/data/postgres
    networks:
      - b-shuli-network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/assets
      - media_volume:/home/app/media
    networks:
      - b-shuli-network
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
