# Generated by Django 4.1.5 on 2023-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('mealtype', models.CharField(choices=[('entree', 'ראשונה'), ('main', 'עיקרית'), ('desert', 'קינוח')], max_length=200)),
                ('mealcat', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='recipe_images')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
