# Generated by Django 4.1.5 on 2023-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/recipe_images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealtype',
            field=models.CharField(max_length=200),
        ),
    ]
