# Generated by Django 4.1.5 on 2023-01-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image_alter_recipe_mealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/media/recipe_images'),
        ),
    ]
