# Generated by Django 4.1.5 on 2023-01-19 22:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
